flaskr/flaskr/views/relation.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, redirect, request, url_for, session, flash
from helpers import conn, cursor, redirect_url
from datetime import datetime
from requete import relationCreate, relationDelete, relationByFollowingIdAndFollowerId, relationGetFollowerUserByFollowingId, relationGetFollowingUserByFollowerId, userByUserId

mod = Blueprint('relation', __name__, url_prefix='/relation',)

@mod.route('/me')
def show_me():
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    return redirect(url_for('relation.show', user_id=session['logged_id']))

@mod.route('/<int:user_id>')
def show(user_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    followers = relationGetFollowerUserByFollowingId(user_id)
    followings = relationGetFollowingUserByFollowerId(user_id)
    followings = add_informations(followings, session['logged_id'])
    followers = add_informations(followers, session['logged_id'])
    return render_template('relation/show.html', followings=followings, followers=followers)

@mod.route('/follow/<int:following_id>')
def follow(following_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    follower_id = session['logged_id']
    r = relationByFollowingIdAndFollowerId(following_id, follower_id)
    if r is not None:
        flash("Your already following this user", 'warning')
    elif following_id == follower_id:
        flash("Your can't follow yourself", 'warning')
    else:
        c_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        relationCreate(following_id, follower_id, c_time)
        flash('You followed %s !' % userByUserId(following_id)['nickname'], 'success')
    return redirect(redirect_url())

@mod.route('/unfollow/<int:following_id>')
def unfollow(following_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    follower_id = session['logged_id']
    relationDelete(following_id, follower_id)
    flash('You unfollowed %s !' % userByUserId(following_id)['nickname'], 'success')
    return redirect(redirect_url())

def add_informations(follows, user_id):
    tmp_follows = []
    for f in follows:
        f = dict(f.items())
        f['is_followed'] = relationByFollowingIdAndFollowerId(f['user_id'], user_id) is not None
        f['is_me'] = f['user_id'] == user_id
        tmp_follows.append(f)
    return tmp_follows

flaskr/flaskr/views/search.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, redirect, request,\
	url_for, session, flash
from helpers import conn, cursor, redirect_url
from datetime import datetime
from requete import searchGetUserResults, relationByFollowingIdAndFollowerId


mod = Blueprint('search', __name__, url_prefix='/search',)

@mod.route('/', methods=['GET', 'POST'])
def new_search():
	if not session.get('logged_in'):
		return redirect(url_for('users.login'))
	if request.method == 'POST':
		search_request = request.form['search'].strip().lower()
		if search_request == '':
			flash("You can't do an empty search", 'danger')
			return redirect(redirect_url())
		return redirect(url_for('search.results', search_request=search_request))
	return redirect(url_for('show_entries'))


@mod.route('/<string:search_request>', methods=['GET', 'POST'])
def results(search_request):
	if not session.get('logged_in'):
		return redirect(url_for('users.login'))
	search = '%' + search_request + '%'
	users = searchGetUserResults(search, session['logged_id'])
	tmp_users = []
	for u in users:
		u = dict(u.items())
		u['is_followed'] = relationByFollowingIdAndFollowerId(u['user_id'], session['logged_id']) is not None
		tmp_users.append(u)
	users = tmp_users
	return render_template('relation/search.html', users=users, search=search_request)

flaskr/flaskr/templates/relation/search.html
{% extends "layout.html" %}
{% block cardtitle %}
  <h2>Search's results</h2>
{% endblock %}
{% block cardbody %}
  <form action="{{ url_for('search.new_search') }}" method=post>
    {{ forms.special_input('search', type='text', value=search, label='Search users...', send_label='🔍', add_pic=False) }}
  </form>
  <hr/>
  {% for u in users %}
    <li class="list-group-item">
      {{ macros.user(user_id=u.user_id, nickname=u.nickname, email=u.email, is_followed=u.is_followed) }}
    </li>
  {% else %}
    <li class="list-group-item"><em>No results.</em></li>
  {% endfor %}
{% endblock %}

flaskr/flaskr/templates/relation/show.html
{% extends "layout.html" %}
{% block body %}
  <div class="card mt-3">
    <div class="card-header"><h2>{{followings|length}} followings</h2></div>
    <div class="card-body">
	  {% for f in followings %}
	    <li class="list-group-item">
      {{ macros.user(user_id=f.user_id, nickname=f.nickname, email=f.email, is_followed=f.is_followed, is_me=f.is_me) }}
	    </li>
	  {% else %}
	    <li class="list-group-item"><em>Unbelievable. You following nobody.</em></li>
	  {% endfor %}
    </div>
  </div>
  <div class="card mt-3">
    <div class="card-header"><h2>{{followers|length}} followers</h2></div>
    <div class="card-body">
	  {% for f in followers %}
	    <li class="list-group-item">
      {{ macros.user(user_id=f.user_id, nickname=f.nickname, email=f.email, is_followed=f.is_followed, is_me=f.is_me) }}
	    </li>
	  {% else %}
	    <li class="list-group-item"><em>Unbelievable. Nobody follow you.</em></li>
	  {% endfor %}
    </div>
  </div>
{% endblock %}