flaskr/flaskr/views/comment.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, redirect, request,\
    url_for, session, flash
from helpers import conn, cursor
from datetime import datetime
from requete import commentCreate, commentByCmtId, commentUpdateById, commentDeleteById

mod = Blueprint('comment', __name__, url_prefix='/comment',)

@mod.route('/add', methods=['GET', 'POST'])
def add():
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    if request.method == 'POST':
        msg_id = int(request.form['msg_id'])
        user_id = session['logged_id']
        content = request.form['content']
        c_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        if content == "":
            flash('Do not send null ', 'warning')
        else:
            commentCreate(msg_id, user_id, content, c_time)
    return redirect(url_for('message.show', msg_id=msg_id))


@mod.route('/edit/<int:cmt_id>', methods=['GET', 'POST'])
def edit(cmt_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    m = None
    if request.method == 'GET':
        m = commentByCmtId(cmt_id)
        return render_template('comment/edit.html', m=m, cmt_id=cmt_id)

    if request.method == 'POST':
        m = commentByCmtId(cmt_id)
        if m['user_id'] == session['logged_id']:
            content = request.form['content']
            commentUpdateById(content, cmt_id)
            flash('Edit Success!', 'success')
        else:
            flash("You are not the owner of this comment! You can't edit it.", 'warning')
        return redirect(url_for('message.show', msg_id=m['msg_id']))

    return render_template('comment/edit.html', m=m, cmt_id=cmt_id)


@mod.route('/delete/<int:cmt_id>', methods=['GET', 'POST'])
def delete(cmt_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        m = commentByCmtId(cmt_id)
        if m['user_id'] == session['logged_id']:
            commentDeleteById(cmt_id)
            flash('Delete Success!', 'success')
        else:
            flash("You are not the owner of this comment! You can't delete it.", 'warning')
    return redirect(url_for('message.show', msg_id=m['msg_id']))


def countcmt(msg_id):
    cursor.execute("SELECT COUNT(*) FROM comment where msg_id = %s;", (msg_id,))
    like_num = cursor.fetchone()
    return like_num[0]

flaskr/flaskr/views/like_cmt.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, redirect, request,\
    url_for, session, flash
from helpers import conn, cursor, redirect_url
from datetime import datetime
from requete import likeCmtCreate, likeCmtDelete

mod = Blueprint('like_cmt', __name__, url_prefix='/like_cmt',)


@mod.route('/like/<int:cmt_id>', methods=['GET', 'POST'])
def like(cmt_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        c_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        likeCmtCreate(cmt_id, session['logged_id'], c_time)
    return redirect(redirect_url())


@mod.route('/unlike/<int:cmt_id>', methods=['GET', 'POST'])
def unlike(cmt_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        likeCmtDelete(cmt_id, session['logged_id'])
    return redirect(redirect_url())

flaskr/flaskr/views/message.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, redirect, request,\
    url_for, session, flash
from helpers import conn, cursor, redirect_url
from datetime import datetime
from requete import messageById, messageCreate, messageDeleteById, messageUpdateContentById, commentByMsgIdOrder, userByUserId, likeCmtGetOne, likeCmtCountLike

mod = Blueprint('message', __name__, url_prefix='/message',)


@mod.route('/<int:msg_id>', methods=['GET', 'POST'])
def show(msg_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    if request.method == 'GET':
        m = messageById(msg_id)
        cs = commentByMsgIdOrder(msg_id)
        final_cs = []
        for c in cs:
            c = dict(c.items())
            c['nickname'] = userByUserId(c['user_id'])['nickname']
            c['like_flag'] = likeCmtGetOne(c['cmt_id'], session['logged_id']) is not None
            c['like_num'] = likeCmtCountLike(c['cmt_id'])
            final_cs.append(c)
    return render_template('message/show.html', m=m, cs=final_cs, user_id=session['logged_id'])

@mod.route('/add', methods=['GET', 'POST'])
def add():
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    if request.method == 'POST':
        user_id = session['logged_id']
        content = request.form['content']
        c_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        if content == "":
            flash('Do not send null ', 'warning')
        else:
            messageCreate(user_id, content, c_time)
    return redirect(url_for('show_entries'))


@mod.route('/edit/<int:msg_id>', methods=['GET', 'POST'])
def edit(msg_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    m = messageById(msg_id)
    if request.method == 'POST':
        if m['user_id'] == session['logged_id']:
            content = request.form['content']
            messageUpdateContentById(content, msg_id)
            flash('Edit Success!', 'success')
        else:
            flash("You are not the owner of this message! You can't edit it.", 'warning')
        return redirect(url_for('show_entries'))

    return render_template('message/edit.html', m=m, msg_id=msg_id)


@mod.route('/delete/<int:msg_id>', methods=['GET', 'POST'])
def delete(msg_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    m = messageById(msg_id)
    if request.method == 'GET':
        if m['user_id'] == session['logged_id']:
            messageDeleteById(msg_id)
            flash('Delete Success!', 'success')
        else:
            flash("You are not the owner of this message! You can't delete it.", 'warning')
    return redirect(url_for('show_entries'))

flaskr/flaskr/views/users.py
# -*- coding: utf-8 -*-
from flask import Flask, Blueprint, render_template, redirect, request,\
    url_for, session, flash
from datetime import datetime
from helpers import conn, cursor
from views import comment, like_msg
from requete import userByEmail, userByNickname, userIdByEmailPassword, userCreate, userUpdateNicknameByEmail, userUpdatePasswordByEmail, userByUserId, messageGetAllFromUserIdOrder, CommentCountCmt, likeMsgCountLike, relationByFollowingIdAndFollowerId, likeMsgGetOne
import re

app = Flask(__name__)
mod = Blueprint('users', __name__, url_prefix='/users',)

@mod.route('/me')
def show_me():
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    return redirect(url_for('users.show', user_id=session['logged_id']))

@mod.route('/<int:user_id>', methods=['GET', 'POST'])
def show(user_id):
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    u = userByUserId(user_id)
    u = dict(u.items())
    u['is_followed'] = relationByFollowingIdAndFollowerId(u['user_id'], session['logged_id']) is not None
    u['is_me'] = u['user_id'] == session['logged_id']
    ms = messageGetAllFromUserIdOrder(user_id)
    entries = []
    for m in ms:
        m = dict(m.items())
        m['nickname'] = userByUserId(m['user_id'])['nickname']
        m['like_flag'] = likeMsgGetOne(m['msg_id'], session['logged_id']) is not None
        m['is_mine'] = m['user_id'] == session['logged_id']
        m['like_num'] = likeMsgCountLike(m['msg_id'])
        m['cmt_num'] = CommentCountCmt(m['msg_id'])
        entries.append(m)
    ms=entries
    return render_template('users/show.html', u=u, ms=ms)

@mod.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form['email'].strip().lower()
        nickname = request.form['nickname'].strip()
        password = request.form['password'].strip()
        password2 = request.form['password2'].strip()
        c_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

        uByEmail = userByEmail(email)
        uByNickname = userByNickname(nickname)

        ret = registerRequest(email, nickname, password, password2, uByEmail, uByNickname)
        if ret != 'Register Success!':
            flash(ret, 'danger')
        else:
            userCreate(email, nickname, password, c_time)
            flash('Register Success!', 'success')
            return redirect(url_for('users.login'))

        # if email == "" or nickname == "" or password == "" or password2 == "":
        #     flash('Please input all the information', 'danger')
        # elif not re.match(r'^[0-9a-zA-Z_]{0,19}@' +
        #                   '[0-9a-zA-Z]{1,15}\.[0-9a-zA-Z]{2,4}', email):
        #     flash('Please input the right email', 'danger')
        # elif uByEmail is not None:
        #     flash('The email already exist', 'danger')
        # elif uByNickname is not None:
        #     flash('The nickname already exist', 'danger')
        # elif password2 != password:
        #     flash('The password is not repeated correctly', 'danger')
        # elif len(password) < 6:
        #     flash('The password should be at least 6 characters', 'danger')
        # else:
        #     userCreate(email, nickname, password, c_time)
        #     flash('Register Success!', 'success')
        #     return redirect(url_for('users.login'))


    return render_template('users/register.html')

@mod.route('/login', methods=['GET', 'POST'])
def login():
    email = ''
    if session.get('logged_in'):
        return redirect(url_for('show_entries'))
    if request.method == 'POST':
        email = request.form['email'].strip().lower()
        password = request.form['password'].strip()

        if email == "" or password == "":
            flash('Please input all the information', 'danger')
        else:
            rep = loginRequest(email, password)
            if rep != "Login Success!":
                flash(rep, 'danger')
            else:
                u = userIdByEmailPassword(email, password)
                session['logged_in'] = True
                session['logged_email'] = email
                session['logged_id'] = u['user_id']
                return redirect(url_for('show_entries'))

        # u = userByEmail(email)

        # if u is None:
        #     flash("The user doesn\'t exsit.Please register first.", 'danger')

        # else:
        #     u = userIdByEmailPassword(email, password)
        #     if u is None:
        #         flash("Your password is wrong.Try it again.", 'danger')
        #     else:
        #         session['logged_in'] = True
        #         session['logged_email'] = email
        #         session['logged_id'] = u['user_id']
        #         return redirect(url_for('show_entries'))

    return render_template('users/login.html', email=email)


@mod.route('/logout', methods=['GET', 'POST'])
def logout():
    session.pop('logged_in', None)
    flash('You were logged out', 'success')
    return redirect(url_for('users.login'))


@mod.route('/edit', methods=['GET', 'POST'])
def edit():
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    if request.method == 'POST':
        newNickname = request.form['nickname']
        uByNickname = userByNickname(request.form['nickname'])
        rep = editNicknameRequest(uByNickname, newNickname)
        if rep != "Edit Nickname Success!":
            flash(rep, "danger")
        else:
            userUpdateNicknameByEmail(request.form['nickname'], session['logged_email'])
            flash('Edit Nickname Success!', 'success')
        # if newNickname == "":
        #     flash('The nickname can not be null', 'danger')
        # elif uByNickname is not None:
        #     flash('The nickname already exist', 'danger')
        # else:
        #     userUpdateNicknameByEmail(request.form['nickname'], session['logged_email'])
        #     flash('Edit Nickname Success!', 'success')
    u = userByEmail(session['logged_email'])
    return render_template('users/edit.html', u=u)


@mod.route('/editPwd', methods=['GET', 'POST'])
def editPwd():
    if not session.get('logged_in'):
        return redirect(url_for('users.login'))
    if request.method == 'POST':
        oldPassword = request.form['oldPassword'].strip()
        newPassword = request.form['newPassword'].strip()
        newPassword2 = request.form['newPassword2'].strip()
        u = userIdByEmailPassword(session['logged_email'], oldPassword)

        rep = editPasswordRequest(u, newPassword, newPassword2)
        if rep != "Edit Password Success!":
            flash(rep, "danger")
        else:
            password = newPassword
            userUpdatePasswordByEmail(password, session['logged_email'])
            flash('Edit Password Success!', 'success')

        # if u is None:
        #     flash("Your old password is not right.", 'danger')
        # elif newPassword != newPassword2:
        #     flash('The password is not repeated correctly', 'danger')
        # elif len(newPassword) < 6:
        #     flash('The password should be at least 6 characters', 'danger')
        # else:
        #     password = newPassword
        #     userUpdatePasswordByEmail(password, session['logged_email'])
        #     flash('Edit Password Success!', 'success')

    u = userByEmail(session['logged_email'])
    return render_template('users/edit.html', u=u)

def editNicknameRequest(uByNickname, newNickname):
    if newNickname == "":
        return 'The nickname can not be null'
    elif uByNickname is not None:
        return 'The nickname already exist'
    else:
        return 'Edit Nickname Success!'

def editPasswordRequest(u, newPassword, newPassword2):
    if u is None:
        return "Your old password is not right."
    elif newPassword != newPassword2:
        return 'The password is not repeated correctly'
    elif len(newPassword) < 6:
        return 'The password should be at least 6 characters'
    else:
        return "Edit Password Success!"


def loginRequest(email, password):
    u = userByEmail(email)

    if u is None:
        return "The user doesn\'t exist. Please register first."
    else:
        u = userIdByEmailPassword(email, password)
        if u is None:
            return "Your password is wrong. Try it again."
        else:
            return "Login Success!"

def registerRequest(email, nickname, password, password2, uByEmail, uByNickname):
    if email == "" or nickname == "" or password == "" or password2 == "":
        return 'Please input all the information'
    elif not re.match(r'^[0-9a-zA-Z_]{0,19}@' + '[0-9a-zA-Z]{1,15}\.[0-9a-zA-Z]{2,4}', email):
        return 'Please input the right email'
    elif uByEmail is not None:
        return 'The email already exist'
    elif uByNickname is not None:
        return 'The nickname already exist'
    elif password2 != password:
        return "The password is not repeated correctly"
    elif len(password) < 6:
        return 'The password should be at least 6 characters'
    else:
        return "Register Success!"

flaskr/flaskr/templates/flash_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    {% for category, message in messages %}
      <div class="alert alert-{{ category }} mt-3" role="alert">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endwith %}

flaskr/flaskr/templates/forms.html
{% macro input(name, value='', type='text', label='', placeholder=label, readonly='') -%}
<div class="form-group">
  <label for="{{ name }}">{{ label }}</label>
  <input type="{{ type }}" class="form-control" name="{{ name }}"  placeholder="{{ placeholder }}" {{ readonly }} value="{{ value|e }}">
</div>
{%- endmacro %}

{% macro textarea(name, value='', label='', placeholder=label, readonly='') -%}
<div class="form-group">
  <label for="{{ name }}">{{ label }}</label>
  <textarea class="form-control" name="{{ name }}" placeholder="{{ placeholder }}" {{ readonly }} >{{ value }}</textarea>
</div>
{%- endmacro %}

{%- macro submit(name) -%}
<button type="submit" class="btn btn-primary">{{ name }}</button>
{%- endmacro %}

{% macro special_input(name, value='', type='text', label='', placeholder=label, readonly='', send_label='Send ➤', add_pic=True) -%}
{% if add_pic %}
<img src="https://i.imgur.com/7gFE5I9.jpg" alt="..." class="rounded-circle profil-pic">
{% endif %}
<div class="input-group">
  <input name="{{ name }}" type="{{ type }}" class="form-control" placeholder="{{ placeholder }}" aria-label="{{ label }}" value="{{ value|e }}" {% if add_pic %} style="margin-left: 56px;"{% endif %} {{ readonly }} >
  <span class="input-group-btn">
    <input class="btn btn-primary" type=submit value="{{ send_label }}"></input>
  </span>
</div>
{%- endmacro %}

flaskr/flaskr/templates/global_var.html
{% set APPLICATION_NAME = 'Flaskr' %}
{% set APPLICATION_NAME_FIRST_LETTER = 'F' %}

flaskr/flaskr/templates/internal_server_error.html
{% extends "layout.html" %}
{% block cardtitle %}
  <h2>Internal Server Error</h2>
{% endblock %}
{% block cardbody %}
  Sorry, our server got some error, please try again later.
{% endblock %}

flaskr/flaskr/templates/layout.html
{% import 'forms.html' as forms %}
{% import 'macros.html' as macros %}
{% import 'global_var.html' as GL %}

<!doctype html>
<html lang="en">
<head>
  {% block head %}
  <title>{% block title %}Page{% endblock %} - {{ GL.APPLICATION_NAME }}</title>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel=stylesheet type=text/css href="{{ url_for('static', filename='main.css') }}">
  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
  {% endblock %}
</head>

<body class="bg-faded">
  {% include 'header.html' %}
  <div class="container">
  {% include 'flash_messages.html' %}
    {% block body %}
      <div class="card mt-3">
        <div class="card-header">{% block cardtitle %}{% endblock %}</div>
        <div class="card-body">{% block cardbody %}{% endblock %}</div>
      </div>
    {% endblock %}
  </div>
  {% include 'footer.html' %}
  <script src="{{ url_for('static', filename='jquery-3.2.1.min.js') }}"></script>
  <script src="{{ url_for('static', filename='popper.js') }}"></script>
  <script src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
</body>
</html>

flaskr/flaskr/templates/macros.html
{% macro message(id='', content='', nickname='', user_id='', like=False, date='', is_comment=False, add_pic=True, is_mine=False, like_num=0, cmt_num=0) -%}
{% if add_pic %}
<img src="https://i.imgur.com/7gFE5I9.jpg" alt="..." class="rounded-circle profil-pic">
{% endif %}
<div class="post-container">
  <a href="{{ url_for('users.show', user_id=user_id) }}" >@{{ nickname }}</a> {{ content|safe }}<br>
  {% if not is_comment %}
    {% if like %}
      <a href="{{ url_for('like_msg.unlike', msg_id=id) }}" class="card-link">Unlike({{ like_num }})</a>
    {% elif not like %}
      <a href="{{ url_for('like_msg.like', msg_id=id) }}" class="card-link">Like({{ like_num }})</a>
    {% endif %}
    <a href="{{ url_for('message.show', msg_id=id) }}" class="card-link">Comment({{ cmt_num }})</a>
    {% if is_mine %}
      <a href="{{ url_for('message.edit', msg_id=id) }}" class="card-link">Edit</a>
      <a href="{{ url_for('message.delete', msg_id=id) }}" onclick="return confirm('Are you sure to delete it?')" class="card-link">Delete</a>
    {% endif %}
  {% else %}
    {% if like %}
      <a href="{{ url_for('like_cmt.unlike', cmt_id=id) }}" class="card-link">Unlike({{ like_num }})</a>
    {% elif not like %}
      <a href="{{ url_for('like_cmt.like', cmt_id=id) }}" class="card-link">Like({{ like_num }})</a>
    {% endif %}
    {% if is_mine %}
      <a href="{{ url_for('comment.edit', cmt_id=id) }}" class="card-link">Edit</a>
      <a href="{{ url_for('comment.delete', cmt_id=id) }}" onclick="return confirm('Are you sure to delete it?')" class="card-link">Delete</a>
    {% endif %}
  {% endif %}
  <span class="float-right text-muted">{{ date }}</span>
</div>
{%- endmacro %}

{% macro user(user_id='', nickname='', email='', is_followed=True, is_me=False) %}
<img src="https://i.imgur.com/7gFE5I9.jpg" alt="..." class="rounded-circle profil-pic">
<div class="post-container"s>
  {% if not is_me and is_followed %} <a class="float-right btn btn-follow btn-outline-primary ml-1" href="{{ url_for('relation.unfollow', following_id=user_id) }}">unfollow</a>
  {% elif not is_me and not is_followed %} <a class="float-right btn btn-follow btn-primary ml-1" href="{{ url_for('relation.follow', following_id=user_id) }}">follow</a>
  {% endif %}
  <a href="{{ url_for('users.show', user_id=user_id) }}" >@{{ nickname }}</a><br>{{ email }}<br>
</div>
{% endmacro %}

{% macro user_informations(user_id='', is_me=False) %}
<a class="card-link post-container" href="{{ url_for('relation.show', user_id=user_id) }}" >Relations</a>
{% if is_me %}
  <a class="card-link" href="{{ url_for('users.edit') }}" >Edit Profil</a>
  <a class="card-link text-danger float-right" href="{{ url_for('users.logout') }}" >Logout</a>
{% endif %}
{% endmacro %}

flaskr/flaskr/templates/page_not_found.html
{% extends "layout.html" %}
{% block cardtitle %}
  <h2>Page not found</h2>
{% endblock %}
{% block cardbody %}
  This page doesn't exist
{% endblock %}

flaskr/flaskr/templates/show_entries.html
{% extends "layout.html" %}
{% block body %}
  {% if session.logged_in %}
  <div class="card mt-3">
    <div class="card-body">
      <form action="{{ url_for('message.add') }}" method=post class=add-entry>
        {{ forms.special_input('content', type='text', placeholder='New post ...') }}
      </form>
    </div>
  </div>
  {% endif %}
  <div class="card mt-3 stream">
  <ul class="entries list-group list-group-flush">
  {% for m in ms %}
    <li class="list-group-item">
      {{ macros.message(id=m.msg_id, content=m.content, nickname=m.nickname, user_id=m.user_id, like=m.like_flag, date=m.c_time, is_mine=m.is_mine, like_num=m.like_num, cmt_num=m.cmt_num) }}
    </li>
  {% else %}
    <li class="list-group-item"><em>Unbelievable.  No messages here so far. Try to write a post or search and follow the user @ulysse.</em></li>
  {% endfor %}
  </ul>
  </div>
{% endblock %}